### PR TITLE
google translate supports

### PR DESCRIPTION
**Pull request by rapidrabbit76**
hello, @butaixianran 

added support for google translator API.
i wanted to try deepl, but I couldn't pay in Korea, so I added an API provided by google and [papago translator](https://papago.naver.com/) (by naver, support soon).
First send a google api function PR.
I am using it well. thank you

스크린샷 2023-02-15 14 16 50

### CODE REVIEW

**Comment by butaixianran** [comment]
Hi, I see you add an install script to use pip install dataclasses_json. 

There is a problem about this. In China, people can not access pip server, it is blocked by national firewall. 
So, with an install script, people gonna be stoped at there and failed to run.

You may not notice that, there are many extensions are created by chinese and none of them uses install script. Because final users are not developers, they have no idea about pip and don't know it's been blocked.

So, if you need dataclasses_json, this is the way chinese developers used:

Do not install it for user, but write it into document, ask user install it by themself, if they want to use google translator.

Then you check if dataclasses_json is installed in your code. If not, you just print error msg to ask them to install that.

Sorry for this, but I have to consider chinese users. Change your code into this way, I'll merge it. Thanks for your effort

**Comment by rapidrabbit76** [comment]
@butaixianran 

sorry,I didn't think of any issues with "pip install".
I will modify the code in a way that does not have dependencies and create and upload a usage document in a separate path.

**Comment by butaixianran** [comment]
You don't have to upload another document. Just modify the readme, or just update the code, then I'll modify the readme

**Comment by rapidrabbit76** [comment]
@butaixianran 

update my code check it

- remove install script 
- update readme (create google translation  api key)

**Pull request merged**
